development:
  adapter: postgresql
  database: self_destructing_messages
  username: postgres
  password: unhackablepassword
  pool: 5

test:
  adapter: postgresql
  database: self_destructing_messages
  username: postgres
  password: unhackablepassword
  pool: 5


production:
  adapter: postgresql
  database: self_destructing_messages
  username: postgres
  password: unhackablepassword
  pool: 5
